pipeline {
    environment {
    imagename = "techscrumbackend-uat-ecr"
    ecrurl = "https://152658500028.dkr.ecr.ap-southeast-2.amazonaws.com/techscrumbackend-uat-ecr"
    ecrcredentials = 'ecr:ap-southeast-2:TechScrumProjectAWS'
    dockerImage = ''
  } 
    agent any

    stages {
        stage('Git checkout') {
            steps{
                // Get source code from a GitHub repository
                git branch:'main', credentialsId:'github-credential', url:'git@github.com:DevOpsTechscrum/DevOps-Techscrum.be.git'
            }
        }
        
        stage('npm install') {
            steps{
                dir("./") {
                    sh 'npm install'
                    sh 'docker builder prune -f'
                }
            }
        }
        
        stage('Tests') {
            steps{
                dir("./") {
                    sh 'npm run test'
                }
            }
        }
    
        stage('Building image') {
            steps{
            script {
          dockerImage = docker.build imagename
        }
      }
    }

    stage('Push Image') {

      steps{
        script {
          docker.withRegistry(ecrurl, ecrcredentials) {     
            //dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')

          }
        }
      }
    }

  }
}
  
    // stage('Publish to AWS EC2') {
    //         steps{
    //             script {

    //               def dockerRun = "aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 508023426757.dkr.ecr.ap-southeast-2.amazonaws.com && \
    //                     docker pull 508023426757.dkr.ecr.ap-southeast-2.amazonaws.com/techscrum-linda:latest && \
    //                     docker run -d --rm -p 8000:8000 508023426757.dkr.ecr.ap-southeast-2.amazonaws.com/techscrum-linda "
    //                  sshagent(credentials : ['techscrum-ec2']) {
    //                     sh "echo pwd"
    //                     sh "ssh ubuntu@13.210.229.250 -o StrictHostKeyChecking=no '${dockerRun}'"
    //                 }
    //              }
    //         }
    //     }
    // }
