pipeline {
    agent any
    stages {
        stage('provision server') {
         
            steps {
                script {
                    dir('./BackendTF/terraform') {
                    withAWS(region:"ap-southeast-2", credentials:"TechScrumProjectAWS"){
                        sh "terraform init"
                        sh "terraform apply --auto-approve"
                        }
                    }
                }
        
           }
        }

    }
}