---
- name: git module demo
  hosts: all
  # become: yes
  # become_user: root
  user: ubuntu

  vars:
    repo: "git@github.com:DevOpsTechscrum/Devops.git"
    dest: "~/devops/techscrum-monitor"
 
  tasks:
    - name: checkout git repo

      git:
        repo: "{{repo}}"
        dest: "{{dest}}"
      