---
- name: git module demo
  hosts: all
  become: yes
  become_user: root
  user: ubuntu

  vars:
    repo: "git@github.com:chaolin1984/yet-another-cloudwatch-exporter.git"
    dest: "~/devops/techscrum-monitor"
    sshkey: "/home/ubuntu/.ssh/id_rsa"
  tasks:
    - name: checkout git repo

      git:
        repo: "{{repo}}"
        dest: "{{dest}}"
        key_file: "{{sshkey}}"