---
- name: git module demo
  hosts: all
  become: yes
  become_user: root
  user: ubuntu

  environment:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_REGION: "ap-southeast-2"

  tasks:
    - name: run yace docker docker-compose
      shell:
        cmd: "AWS_REGION=ap-southeast-2 AWS_PROFILE=default docker-compose up -d"
        chdir: "/root/devops/techscrum-monitor/docker-compose"
      # community.docker.docker_compose:
      #   project_src: "~/devops/techscrum-monitor/docker-compose"
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output