pipeline {
    agent any

    environment {
        PRIVATE_KEY = credentials('jenkins_node')
    }

    stages {
        stage('Git checkout') {
            steps{
                // Get source code from a GitHub repository
                
                git branch:'monitor-ansible', credentialsId:'jenkins_node', url:'git@github.com:DevOpsTechscrum/Devops.git'
            
            }
        }
        // run docker
        stage('run docker') {
            steps{
                dir("./monitor/ansible-playbook/ansible-playbook-plain") {
                    ansiblePlaybook (credentialsId: 'monitor-ec2-key', inventory: '../inventory.aws_ec2.yaml', playbook: './docker.yaml')
                }
            }
        }
        
        stage('Checkout from GitHub') {
            steps{
                dir("./monitor/ansible-playbook/ansible-playbook-plain") {
                withCredentials([sshUserPrivateKey(credentialsId: 'jenkins_node', keyFileVariable: 'SSH_KEY')]) {
                //sh 'export GIT_SSH_COMMAND="ssh -i $SSH_KEY"'
                ansiblePlaybook (credentialsId: 'monitor-ec2-key', inventory: '../inventory.aws_ec2.yaml', playbook: './git.yaml', extraVars: [private_key_content: readFile(keyFile)],)
                }
            }
            }
    }


        // stage('run git') {
        //     steps{
        //         dir("./monitor/ansible-playbook/ansible-playbook-plain") {
        //             sh 'ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts'
        //             sshagent(credentials: ['jenkins_node']) {
        //                 ansiblePlaybook (credentialsId: 'monitor-ec2-key', inventory: '../inventory.aws_ec2.yaml', playbook: './git.yaml')
        //             }
        //         }
        //     }
        // }

        // stage('run yace') {
        //     steps{
        //         dir("./ansible-playbook") {
        //             sh 'ansible-playbook -i ../inventory.aws_ec2.yaml git.yaml'
        //         }
        //     }
        // }


        // stage('run yace'){
        //     steps{
        //         dir("./ansible-playbook"){
        //         withAWS(region:"ap-southeast-2", credentials:"jenkins_aws"){
        //             // s3Delete(bucket: "${env.UATS3BucketName}", path:'**/*')
        //             s3Upload(bucket: "techscrum-linda-frontend", workingDir:'build', includePathPattern:'**/*');
        //             }
        //         } 
        //     }   
        // }
    }
}
