# ---
# filters:
#   tag:Project: techscrum
# keyed_groups:
#   - key: tags['Name']
#     prefix: tag
# plugin: aws_ec2
# # Populate inventory with instances in these regions
# regions:
#   - ap-southeast-2
#     # so the groups are tag_web and tag_redis

all: 
  hosts:
    ec2-13-239-112-205.ap-southeast-2.compute.amazonaws.com: