def s3_bucketname
pipeline {
    agent any

    

    stages {
        stage('Git checkout') {
            steps{
                // Get source code from a GitHub repository
                
                git branch:'main', credentialsId:'github-credential', url:'git@github.com:DevOpsTechscrum/DevOps-Techscrum.fe.git'
            
            }
        }
        // CI
        stage('npm install') {
            steps{
                dir("./") {
                    sh 'yarn install'
                }
            }
        }
        
        stage('Build') {
            steps{
                dir("./") {
                    sh 'yarn build'
                }
            }
        }
    
// CD

        stage("Upload"){
            steps{
                dir("./"){
                withAWS(region:"ap-southeast-2", credentials:"TechScrumProjectAWS"){
                    // s3Delete(bucket: "${env.UATS3BucketName}", path:'**/*')
                    s3Upload(bucket: "techscrum-linda-frontend", workingDir:'build', includePathPattern:'**/*');
                    }
                } 
            }   
        }
    }
}